// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gamebox.Data;

#nullable disable

namespace gamebox.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907141310_AddUmlTables")]
    partial class AddUmlTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CustomListGame", b =>
                {
                    b.Property<int>("CustomListsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesInListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomListsId", "GamesInListId");

                    b.HasIndex("GamesInListId");

                    b.ToTable("CustomListGame");
                });

            modelBuilder.Entity("GameMember", b =>
                {
                    b.Property<int>("FavoriteGamesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FavoritedById")
                        .HasColumnType("INTEGER");

                    b.HasKey("FavoriteGamesId", "FavoritedById");

                    b.HasIndex("FavoritedById");

                    b.ToTable("MemberFavoriteGames", (string)null);
                });

            modelBuilder.Entity("GameMember1", b =>
                {
                    b.Property<int>("InToPlayOfId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToPlayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InToPlayOfId", "ToPlayId");

                    b.HasIndex("ToPlayId");

                    b.ToTable("MemberToPlayGames", (string)null);
                });

            modelBuilder.Entity("GameMember2", b =>
                {
                    b.Property<int>("PlayedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayedGamesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayedById", "PlayedGamesId");

                    b.HasIndex("PlayedGamesId");

                    b.ToTable("MemberPlayedGames", (string)null);
                });

            modelBuilder.Entity("gamebox.Models.CustomList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("CustomLists");
                });

            modelBuilder.Entity("gamebox.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageRating")
                        .HasColumnType("REAL");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Studio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("gamebox.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("MemberId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("gamebox.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("gamebox.Models.Administrator", b =>
                {
                    b.HasBaseType("gamebox.Models.User");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("gamebox.Models.Member", b =>
                {
                    b.HasBaseType("gamebox.Models.User");

                    b.HasDiscriminator().HasValue("Member");
                });

            modelBuilder.Entity("CustomListGame", b =>
                {
                    b.HasOne("gamebox.Models.CustomList", null)
                        .WithMany()
                        .HasForeignKey("CustomListsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gamebox.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesInListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameMember", b =>
                {
                    b.HasOne("gamebox.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("FavoriteGamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gamebox.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("FavoritedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameMember1", b =>
                {
                    b.HasOne("gamebox.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("InToPlayOfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gamebox.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("ToPlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameMember2", b =>
                {
                    b.HasOne("gamebox.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("PlayedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gamebox.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("PlayedGamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gamebox.Models.CustomList", b =>
                {
                    b.HasOne("gamebox.Models.Member", "Member")
                        .WithMany("MyCustomLists")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("gamebox.Models.Review", b =>
                {
                    b.HasOne("gamebox.Models.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gamebox.Models.Member", "Member")
                        .WithMany("MyReviews")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("gamebox.Models.Game", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("gamebox.Models.Member", b =>
                {
                    b.Navigation("MyCustomLists");

                    b.Navigation("MyReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
